export * from "./AboutUs";
export * from "./Banner";
export * from "./Contact";
export * from "./ContactUs";
export * from "./CookieAccepter";
export * from "./GetTheApp";
export * from "./Insurance";
export * from "./Promotion"
export * from "./SuitInsurance";
export * from "./WhyChooseUs";